### ISSUE TITLE
frequent releases

### ISSUE THREAD

**Issue by bmesuere** [Avansai/resolve-accept-language#10]
Is there a specific reason why a new version is released so often? If only the dev dependencies are updated, I see no reason for a new release, but maybe I'm missing something.

**Comment by nbouvrette** [comment]
You bring up a valid point, @bmesuere, given that this package only has dev dependencies.

One tangible benefit might come into play if dev dependencies influence the build outputs, such as when updating the TypeScript version. However, such instances are infrequent, and the impact on end-users is likely minimal.

There are also a couple of indirect advantages:

1) It gives a clear indication that the package is actively maintained (in this case, based on your question, it might be a bit too much).
2) Regular updates help in preemptively addressing potential vulnerabilities. But given these are dev dependencies, the urgency is less pronounced, and it shouldn't raise any flags during package installation.

I've been applying this update strategy across all the packages I maintain. Some genuinely benefit from these consistent updates. But I'm considering a more tailored approach for this one, updating only when there's a substantial change.

Out of interest, what prompted the question? Is there an impact on your side, or is it just general curiosity?

**Comment by bmesuere** [comment]
We're using your package as a dependency for a vitepress website which has weekly dependabot updates enabled. This is mainly to keep vitepress up to date which is gearing towards a final release. This also means that every week a PR for this package is created, most of the time with an empty changelog. I was curious to why this was.

Now that I know that there are indeed hardly any changes, I may exclude it from dependabot updates.

(Thank you by the way for maintaining it!)

**Comment by nbouvrette** [comment]
Thanks for the explanations. Here are the general rules I try to follow:

1) Non-impacting releases will use a patch version (I do this almost every week).
2) Releases with some impact but no breaking changes will bump the minor version (this could be for a bug fix).
3) Breaking changes will bump the major version.

You might consider configuring your Dependabot to ignore patch versions to reduce the notifications.

I will close this issue for now but don't hesitate to reach out if you have any questions or feedback!
