### ISSUE TITLE
Underscores aren't properly parsed

### ISSUE THREAD

**Issue by peterj35-dd** [Avansai/resolve-accept-language#2]
Hi @nbouvrette, thank you for the fantastic library! 🙌 

One question though, should underscores also be considered in the resolving algorithm?

For example:

```
var resolveAcceptLanguage = require("resolve-accept-language")

console.log(
  resolveAcceptLanguage.default('de_DE;q=0.01,en-CA;q=0.1,en-US;q=0.001', ['en-US', 'fr-CA', 'de-DE'], 'en-US')
);
```
I would expect to be parsed to `de-DE` but results in `en-US` instead.

Wondering if this is intended behaviour and if so how come (for my own knowledge), or if this is ~~a bug~~ (edit: an improvement that makes sense for the library to have).

**Comment by nbouvrette** [comment]
Thanks @peterj35-dd !

Do you have use cases on why underscore would be used?

Based on https://datatracker.ietf.org/doc/html/rfc5646#section-2.1

> A language tag is composed from a sequence of one or more "subtags", each of which refines or narrows the range of language identified by the overall tag.  Subtags, in turn, are a sequence of alphanumeric characters (letters and digits), distinguished and separated from other subtags in a tag by a hyphen ("-", [Unicode] U+002D).

**Comment by nbouvrette** [comment]
Yes, Java uses underscore for the bundle names and also uses legacy codes for backward compatibility.

But this library's main goal is to resolve `accept-language` HTTP headers and I am not sure what use case would use underscores in this context? If you look in your browser setting, only the most recent BCP 47 language tags will be supported.

Unless you can find me a common/standard use case, I would rather not add this option in our library. But.. if you really want, you could do it yourself like this:

```
var resolveAcceptLanguage = require("resolve-accept-language").default;
var acceptLanguageHeader = 'de_DE;q=0.01,en-CA;q=0.1,en-US;q=0.001'.replace(/_/g, '-');

console.log(
  resolveAcceptLanguage(acceptLanguageHeader, ['en-US', 'fr-CA', 'de-DE'], 'en-US')
);
```
