### ISSUE TITLE
Feature request - Allow callers to discover when no languages match

### ISSUE THREAD

**Issue by spalte** [Avansai/resolve-accept-language#3]
Thank you for you great package.

In the event that no languages match, it can be interesting to serve language agnostic content (such as a language selector) rather than content in an arbitrary default language. Unfortunately the current API does not allow the caller to identify when no languages match. A suggested API might be to allow `undefined` to be passed as the default language, which would result in `undefined` being returned when no matches are found. This would admittedly make the return typing dirtier since it would force callers to check for `undefined` even when a default language was provided.

**Comment by productdevbook** [comment]
some

**Comment by nbouvrette** [comment]
@spalte @productdevbook  sorry for the delay - just saw this issue now. I was trying to think of ways to resolve this.

I think maybe adding a new `ResolveAcceptLanguage` object could be a good option. and then having two new APIs on the object (class):

- `hasFallbackToDefault()` : boolean
- `getMatch()`: current response

I can think more about the naming itself... but it looks like it could meet what you describe?

Let me know what you think and I can implement this relatively quickly. I would also keep the current API so the change would be backward compatible.

**Comment by nbouvrette** [comment]
So I ended up adding a lot more granularity to detect the type of match in this commit: https://github.com/Avansai/resolve-accept-language/commit/dee64298e28e921f7e4e491e50948200f5030b1b

The new 1.1 package should have all you need so I will close this feature request - feedback is always welcomed!

Thanks for the idea @spalte @productdevbook
